### ISSUE TITLE
Feature Request: dom child iteration via __iter__

### ISSUE THREAD

**Issue by bannsec** [d0c-s4vage/pfp#119]
## Is your feature request related to a problem? Please describe
Not really a "problem". More that I find it not terribly intuitive to write dom._pfp__children.

## Describe the solution you'd like
My natural response to iterating through a list of object is to use something like "for item in dom". In this case, my proposed solution would be to implement `__iter__` as simply `return self._pfp__children.__iter__()`.

## Describe alternatives you've considered
Currently I just reference ._pfp__children when I want to see the listing.

## Additional context
N/A

**Comment by d0c-s4vage** [comment]
This makes sense! Thanks for the suggestion

**Comment by d0c-s4vage** [comment]
Eventually I want to do something cleaner than prefixing all internal functions with `_pfp__` too
