### ISSUE TITLE
is there a way not to use external C preprocessor ?

### ISSUE THREAD

**Issue by mtivadar** [d0c-s4vage/pfp#21]
Maybe some C preprocessor written in python.. if there is one, I haven't looked.
Also, it would be great to be possible to pass "use_cpp" arg to py010parser's parse_string()

**Comment by d0c-s4vage** [comment]
good idea. I shoudl add this in

**Comment by d0c-s4vage** [comment]
A pull request for this was submitted and merged into the py010parser project by @synalysis. See https://github.com/d0c-s4vage/py010parser/pull/6 for more details.

pfp no longer uses the external `cpp` preprocessors.

**Comment by d0c-s4vage** [comment]
Also note that these changes have not yet been pushed up to PyPI - waiting to wrap up pfp issues before pushing up the new pfp and py010parser versions.
