### ISSUE TITLE
Error on Parse without using _file

### ISSUE THREAD

**Issue by zachriggle** [d0c-s4vage/pfp#23]
```
>>> pfp.parse('',template='')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-2a3475257e4f> in <module>()
----> 1 pfp.parse('',template='')

/usr/local/google/home/riggle/.pyenv/versions/2.7.9/lib/python2.7/site-packages/pfp/__init__.pyc in parse(data, template, data_file, template_file, interp, debug, predefines, int3, cpp_path, cpp_args, keep_successful)
     62         data = BitwrappedStream(data)
     63 
---> 64         dom = interp.parse(data, template, predefines=predefines, orig_filename=orig_filename, keep_successful=keep_successful)
     65 
     66         # close the data stream if a data_file was specified

/usr/local/google/home/riggle/.pyenv/versions/2.7.9/lib/python2.7/site-packages/pfp/interp.pyc in parse(self, stream, template, predefines, orig_filename, keep_successful)
    668                 self._dlog("parsed template into ast")
    669 
--> 670                 res = self._run(keep_successful)
    671                 return res
    672 

/usr/local/google/home/riggle/.pyenv/versions/2.7.9/lib/python2.7/site-packages/pfp/interp.pyc in _run(self, keep_successfull)
    867                                 more_info = "\nException at {}:{}".format(
    868                                         self._orig_filename,
--> 869                                         self._coord.line
    870                                 )
    871                                 six.reraise(

AttributeError: 'NoneType' object has no attribute 'line'
```

**Comment by ghost** [comment]
Checking the source shows its _impossible_ to run pfp.parse without an input file other than the template.

If you import pfp then check __file__:
>>> pfp.__file__
The interpreter will point you to __init__.py

if you check pfp.parse() in ...\pfp__init__.py it clearly throws an error message if no data file argument is given to parse():

> > > LINE15:    def parse(data=None, template=None, data_file=None, template_file=None, interp=None, debug=False, predefines=True, int3=True, cpp_path="cpp", cpp_args="-xc++", keep_successful=False);
> > > ...
> > > LINE 19:    :data: Input stream (yes, a STREAM, not str)
> > > ...
> > > LINE 21:    :data_file: path ot the data to be used as the input stream
> > > ...
> > > LINE 32:    if data is None and data_file is None:
> > > LINE 33:    ->    raise Exception("No input data was specified")

**Comment by d0c-s4vage** [comment]
Is this coming from the perspective of wanting to create data from structures defined in a template without having to initially parse anything?

**Comment by d0c-s4vage** [comment]
I know I did some work to make creating data from structures in a template pretty simple, but I think I did overlook this aspect of it.

**Comment by zachriggle** [comment]
This might be solvable with use of StringIO types

**Comment by d0c-s4vage** [comment]
```
Python 3.4.3+ (default, Oct 14 2015, 16:03:50) 
[GCC 5.2.1 20151010] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pfp
>>> pfp.parse("", template="")
<pfp.fields.Dom object at 0x7f6d82a35320>
```
