### ISSUE TITLE
Compound types in enums are unsupported

### ISSUE THREAD

**Issue by vit9696** [d0c-s4vage/pfp#24]
Multiword types like "unsigned short" or "unsigned char" are causing a parse error when used in enum declarations. E. g.

```
enum <unsigned short> MY_ENUM {
    VAL_1 = 0,
    VAL_2 = 1
};
```

If one creates a typedef and replaces the type by a single word, it will be ok. I. e.

```
typedef unsigned short u16;
enum <u16> MY_ENUM {
    VAL_1 = 0,
    VAL_2 = 1
};
```

**Comment by d0c-s4vage** [comment]
This is a py010parser error - closing here and recreating in that project.
