### ISSUE TITLE
Improper structure support

### ISSUE THREAD

**Issue by vit9696** [d0c-s4vage/pfp#26]
pfp seems to work very bad with structure typedefing.

Something like that would work with both template parsers (010 Editor and pfp):

```
typedef struct MY_STRUCT_S {
    char magic[4];
    unsigned int filesize;
} MY_STRUCT;
LittleEndian();
MY_STRUCT s;
```

The rest will fail with all kinds of errors in pfp:

```
struct MY_STRUCT {
    char magic[4];
    unsigned int filesize;
};
LittleEndian();
MY_STRUCT s;
```

```
typedef struct MY_STRUCT {
    char magic[4];
    unsigned int filesize;
};
LittleEndian();
MY_STRUCT s;
```

```
struct MY_STRUCT {
    char magic[4];
    unsigned int filesize;
};
LittleEndian();
struct MY_STRUCT s;
```

```
struct MY_STRUCT {
    char magic[4];
    unsigned int filesize;
};
typedef struct MY_STRUCT ME;
LittleEndian();
ME s;
```

And I suppose it is not the end. Pretty much the same happens to enums, for example.

**Comment by d0c-s4vage** [comment]
You're great at finding errors for py010parser :^)

Closing here and recreating it over there. Wish there was an easier way to do that.

**Comment by d0c-s4vage** [comment]
Sigh. This issue does belong in pfp and not py010parser.

Currently all test cases pass except for the last one

**Comment by d0c-s4vage** [comment]
This is really biting pfp right now. I think a lot of the `struct` support needs to be rethought/reworked

**Comment by d0c-s4vage** [comment]
@vit9696 thanks so much for reporting these issues! it's taken a while, but things are slowly shaping up :^)

**Comment by vit9696** [comment]
@d0c-s4vage no problem, actually we opensourced [the script](https://github.com/umineko-project/umineko-scripting/blob/master/extraction/ps3snr/snr.bt) that we used to report our issues from. Binary files are [here](https://github.com/umineko-project/umineko-scripting/tree/master/snr/source). It is quite complex, so it can be a nice test for pfp.
