### ISSUE TITLE
Incorrect variable array support

### ISSUE THREAD

**Issue by vit9696** [d0c-s4vage/pfp#29]
There is no way to pass an array as a function argument in pfp. The following code works just fine in 010 Editor:

```
void passMe(char value[]) {
    Printf("%s\n", value);
}
char me[1024];
passMe(me);
```

**Comment by d0c-s4vage** [comment]
Hrmm... good points.

For my reference, this isn't just a case of `char[]` being treated specially. This also works just fine:

``` c
void passMe(int value[]) {
    Printf("%08x\n", value[0]);
}
int me[5];
passMe(me);
```
