### ISSUE TITLE
Function declaration positions

### ISSUE THREAD

**Issue by vit9696** [d0c-s4vage/pfp#30]
The following code executes just fine in 010 Editor and prints "Hello World". pfp does not see hello function.

```
hello();
void hello() {
    Printf("Hello World\n");
}
```

**Comment by d0c-s4vage** [comment]
![image](https://user-images.githubusercontent.com/5090146/65375321-e046c080-dc48-11e9-90a0-9cb3470eb38c.png)

**Comment by d0c-s4vage** [comment]
![image](https://user-images.githubusercontent.com/5090146/65375399-06209500-dc4a-11e9-8754-2237a42dd5d4.png)

**Comment by d0c-s4vage** [comment]
Will need some testing, but may need to also open another issue in d0c-s4vage/py010parser if nested/non-top-level functions are currently allowed by py010parser
