### ISSUE TITLE
Please make -xc++ the default for cpp_args

### ISSUE THREAD

**Issue by moyix** [d0c-s4vage/pfp#4]
The option doesn't seem to affect anything under gcc, so it should be safe to leave on by default. And it means that for example `pfp-vim` will work out of the box on OS X, which it does not right now.

**Comment by d0c-s4vage** [comment]
Good point. I'll do some more testing on that and push up another release.
I also have some python vs python3 vim support changes to go into pfp-vim
as well.

**Comment by d0c-s4vage** [comment]
Done. Thanks @moyix !

**Comment by d0c-s4vage** [comment]
(changes pushed out with v0.1.9)
