### ISSUE TITLE
Disable Template Printf

### ISSUE THREAD

**Issue by zachriggle** [d0c-s4vage/pfp#45]
Template `printf` statements are useful for debugging, but for library usage (e.g. use by other modules), it's generally undesirable.

A few possible suggestions:

- Global boolean which controls `printf`
  - Default to `True`
- Hook function which intercepts `printf`
  - Default to a wrapper around `sys.stdout.write`
  - Should not directly default to `sys.stdout` object at init-time since that object is frequently hooked

**Comment by d0c-s4vage** [comment]
Hrmm, I thought I added something like this already...

**Comment by zachriggle** [comment]
I didn't see anything in the `Printf` implementation itself, but admittedly did not look further.

**Comment by d0c-s4vage** [comment]
`pfp.parse(..., printf=False)` now exists :^)
