### ISSUE TITLE
Can't compare to Hex value

### ISSUE THREAD

**Issue by bobfrogg** [d0c-s4vage/pfp#56]
With
06 D0 DE FA  in a file,
int DEFA; in the template
I can do if(DEFA==0xFADED006) in the template, but in pfp this fails, I have to write it as ==-86061050

**Comment by d0c-s4vage** [comment]
Really? Wow. I'll check this out. Thanks for the report!

**Comment by d0c-s4vage** [comment]
Confirmed
![image](https://user-images.githubusercontent.com/5090146/66178639-d9da2080-e61a-11e9-9c25-ce9562c00b73.png)

**Comment by d0c-s4vage** [comment]
This fix landed in version 0.3.0, closing
